### ISSUE TITLE
Error al crear modelo

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2143-2020-2/syllabus#145]
Hola hace un par de días cree un modelo "carrete" en una carpeta aparte para practicar, pero ahora estoy intentado hacerlo en mi proyecto y cada vez que hago el modelo y luego lo intento hacer migrar, me dice que el modelo "carrete" ya existe y que no lo puede migrar porque se duplica en la talba. para repararlo intenté "bin/rails db:migrate RAILS_ENV=development" pero me migra el modelo carretes que tenía antes y que estaba incompleto. No se que pasa :(

**Comment by jerosalazar** [comment]
Hola! Esto quizas puede pasar porque la bdd de tu proyecto de prueba y la del proyecto de tu grupo se llaman igual, si este es el caso cuando creaste el modelo de prueba, creaste una tabla en la bdd y al querer correr la migración en tu proyecto tienes conflictos con la tabla anterior.
Lo que puedes hacer en este caso ir a tu proyecto semestral y hacer lo siguiente:
* botar la base de datos `rails db:drop`
* crear la base de datos de nuevo `rails db:create`
* correr de nuevo las migraciones `rails db:migrate`

**Comment by jerosalazar** [comment]
como recomendación, fijate que tus bases de datos no tengan el mismo nombre. Esto lo puedes ver en tu archivo `config/database.yml`, que se vería algo asi (mas o menos):
```
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:

production:
  <<: *default
  database: my_app_production

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test
```

La convención en este caso es que cambies "my_app" por el nombre de tu proyecto para que no ocurran problemas como el que mencionaste
