### ISSUE TITLE
Error Paso 7 [mac]

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2143-2020-2/syllabus#94]
Tengo Mac y me salió este error en el paso 7 y no supe como arreglarlo ayuda :(
![Captura de pantalla 2020-09-01 a la(s) 05 03 04](https://user-images.githubusercontent.com/48481963/91830340-a6c85480-ec10-11ea-9517-217105dcb480.png)

**Comment by cchauriye** [comment]
Hola!

Prueba corriendo `sudo -u postgres psql`. Sino prueba con homebrew, usando e comando `brew install libpq`.

**Comment by johnowenatala** [comment]
En mac no debieras hacer eso. La base de datos viene lista para que te conectes usando como usuario tu usuario de sistema (beatrizacunasepulveda) y como contraseña vacío.

En otras palabras, omite el paso 7 y en el paso 9 completas el archivo database.yml con algo como esto (extracto):

```
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <tu usuario de mac>
  password:
  pool: 5
```

**Comment by jerosalazar** [comment]
Hola @beatrizacuna ! te funcionó?

**Comment by beatrizacuna** [comment]
Más o menos jaja, es que como omití el paso 7, no sé que contraseña poner en el paso 9, o no pongo nada?

**Comment by cirey1** [comment]
Hola @beatrizacuna,

Tal como dijo el profesor @johnowenatala. El setup de MacOS es un poco distinto que el de WSL. Por lo tanto, dentro de tu archivo database.yml tienes que utilizar lo que escribió el profesor.

```
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: beatrizacunasepulveda
  password:
  pool: 5
```

En teoría, tu password queda vacía por default. Ahora después de copiar esa parte del código. Deberías poder crear tus bases de datos con ``` rails db:create ```.

P.D: Si te llegase a pasar que te tira error de conexión, esto quiere decir que tu servidor psql no esta corriendo. Para eso, tienes que correr este comando ``` brew services start postgresql ```

Saludos y cuéntanos si te funciona,
